### PR TITLE
add rp1210 support to pretty_j1587

### PR DESCRIPTION
**Pull request by BenGardiner**
corresponds to changes in https://github.com/TruckHacking/py-hv-networks/pull/7

### CODE REVIEW

**Review by salnoobie — CHANGES_REQUESTED** [review]
I don't see the new --J1708-interface option in the parser.add_argument() work within pretty_j1587.py, but I do see it in the Usage comments. Can you confirm?

**Comment by salnoobie** [comment]
Probably same thing with rp1210 options

**Review by salnoobie — APPROVED** [review]

**Comment by salnoobie** [comment]
NVM, I see thee magic now.

**Comment by BenGardiner** [comment]
Yeah, the additional options are added by a helper function in the j1587
driver factory.

**Pull request merged**
